### ISSUE TITLE
ETS Project File import failing with Unknown Error

### ISSUE THREAD

**Issue by eC0y0te** [XKNX/xknxproject#379]
Hi,

I am running a fresh install of Home Assistant OS on Raspberry 5 (HA Core 2024.3.0), with the KNX integration installed (v 2.12.2).

Trying to import my ETS6 Project file unfortunately systematically results in an "**Upload failed**" dialog box with an "**Unknown error**" message. I am happy to share my .knxproj file over private message if it can help. Other than that, happy to provide log files or to perform any steps that may help troubleshoot this issue.

Other than that, the KNX integration is working flawlessly, and I can both control KNX devices from HA and expose HA entities to the KNX bus, with the help of a knx: section I've manually populated in my configuration.

Thank you!

**Comment by farmio** [comment]
Hi 👋! 
Thanks for filing this issue!

We'd need some more information about the error. An excerpt of your logs would be a good start. Depending on what we find there, we'll see about the project file 😉👍

**Comment by eC0y0te** [comment]
Hi Farmio,

I've copied below what I beleive to be the relevant log extract. Let me know if there is a verbose mode I may enable to allow for more detail, or if the KeyError string in full would be useful.

Thanks!

2024-03-12 21:10:30.467 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546887409984] Error handling message: Unknown error (unknown_error) XXX from XXX
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/knx/websocket.py", line 126, in ws_project_file_process
    await knx.project.process_project_file(
  File "/usr/src/homeassistant/homeassistant/components/knx/project.py", line 110, in process_project_file
    project = await self.hass.async_add_executor_job(_parse_project)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/knx/project.py", line 108, in _parse_project
    return xknxproj.parse()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/xknxproject/xknxproj.py", line 41, in parse
    project = XMLParser(knx_project_content).parse(self.language)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/xknxproject/xml/parser.py", line 142, in parse
    self._load(language=language)
  File "/usr/local/lib/python3.12/site-packages/xknxproject/xml/parser.py", line 243, in _load
    device.merge_application_program_info(_application)
  File "/usr/local/lib/python3.12/site-packages/xknxproject/models/models.py", line 193, in merge_application_program_info
    com_instance.merge_application_program_info(application)
  File "/usr/local/lib/python3.12/site-packages/xknxproject/models/models.py", line 310, in merge_application_program_info
    com_object_ref = application.com_object_refs[self.com_object_ref_id]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'M-0071_....'

**Comment by farmio** [comment]
Yes, the full KeyError string could be useful. It points to a specific part of a product application. Knowing the product, I could try to create a test project including the device. 

On the other hand, it would be way easier in this case, if you could send me your project file 🙂 so I can just look it up there.

**Comment by eC0y0te** [comment]
The full KeyError string is: 'M-0071_A-5521-37-37C5_MD-4_SM-1_M-1_MI-1-1-1_SM-1_O-3-0_R-3'

I do have TMD's, Z35's and a Z100 from Zennio. The Z100 configuration in particular is quite rich in ETS, I wouldn't be surprised if it can cause challenges with parsing...

I'll prepare a copy of my knxproj file, that I'll share with you over private message later today.

Thank you!!

**Comment by dwemel** [comment]
Following, as I have the same error!

**Comment by farmio** [comment]
@dwemel do you also have a "Zennio Z100" in your project?

**Comment by dwemel** [comment]
Not the Z100, but I do have the Zennio Z50 and Z70 displays.

Thank you for asking! Hoping for a solution soon :-)

**Comment by farmio** [comment]
Working on it, but so far the Z100 has the only device application I have seen so far, that uses SubModules. 
It would be great if I had more examples so I don't have to reverse engineer this with a sample of 1. 
I'll look into the Z70 🙃.

**Comment by dwemel** [comment]
Thank you! Please let me know if I can help you with something.

Op do 4 apr 2024 19:01 schreef Matthias Alphart ***@***.***>:
